name: fitness_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  simple_animated_icon: ^1.1.0
  expandable_page_view: ^1.0.13
  fading_edge_scrollview: ^2.0.1
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  fluttericon: ^2.0.0
  google_fonts: ^2.3.1
  scrollable_positioned_list: ^0.2.3
  simple_speed_dial: ^0.1.6
  syncfusion_flutter_charts: ^20.1.51
  wheel_chooser: ^1.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
